[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
console_log = { version = "0.2.0", features = ["wasm-bindgen"] }
log = "0.4.17"
sycamore = "0.8.0"
