[package]
name = "quic_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4"
actix-web-actors = "4.1.0"
tokio = { version = "1.21.1", features = ["full"] }
parking_lot = "0.12.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
quinn = "0.8.5"
rustls = { version = "*", features = ["dangerous_configuration", "quic"] }
futures-util = "0.3.24"
anyhow = "1.0.65"
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }
clap = { version = "3.2.22", features = ["derive"] }
chrono = "0.4"
