[package]
name = "storm_grok"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4"
actix-codec = "0.5.0"
actix-web-actors = "4.1.0"
awc = "3"
openssl = { version = "0.10" }

clap = { version = "3", features = ["derive"] }
env_logger = "0.9"
log = "0.4"
url = "2.2"
uuid = { version = "1.1.2", features = ["v4", "fast-rng"] }
futures = "0.3"
futures-util = "0.3.24"

serde = { version = "1.0.144", features = ["derive"] }
bincode = "1.3.3"
async-trait = "0.1.57"
