[package]
name = "shared_types"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "*", features = ["serde"] }
serde = { version = "*", features = ["derive"] }
base64 = "0.21.4"
base64-serde = "*"
